// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { createClient } from "@supabase/supabase-js";

const lovableAuth = createLovableAuth({});

function getSupabaseClient() {
  const url = import.meta.env.VITE_SUPABASE_URL || "https://qvbqzenpxsduhhhikbcx.supabase.co";
  const key = import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2YnF6ZW5weHNkdWhoaGlrYmN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0MTU4NjUsImV4cCI6MjA4NTk5MTg2NX0.QegWahbjFcbopke8fnnUbvrZa7Lrcc6WKQVWN3vDiNw";
  return createClient(url, key);
}

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple", opts?: SignInOptions) => {
      const result = await lovableAuth.signInWithOAuth(provider, {
        redirect_uri: opts?.redirect_uri,
        extraParams: {
          ...opts?.extraParams,
        },
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      try {
        console.log("[LOVABLE-AUTH] OAuth callback received, setting session...");
        console.log("[LOVABLE-AUTH] Tokens received:", { 
          hasAccessToken: !!result.tokens?.access_token, 
          hasRefreshToken: !!result.tokens?.refresh_token 
        });
        const supabaseClient = getSupabaseClient();
        console.log("[LOVABLE-AUTH] Supabase client created:", !!supabaseClient);
        await supabaseClient.auth.setSession(result.tokens);
        console.log("[LOVABLE-AUTH] Session set successfully on lovable client");
        
        // Verify session was stored
        const { data: checkSession } = await supabaseClient.auth.getSession();
        console.log("[LOVABLE-AUTH] Session verification:", { 
          hasSession: !!checkSession?.session,
          userId: checkSession?.session?.user?.id,
          email: checkSession?.session?.user?.email 
        });
      } catch (e) {
        console.error("[LOVABLE-AUTH] Error setting session:", e);
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};
